#!/bin/sh

BUS="0"
ADDR="0x51"
TIMEOUT="0x1E" # 30 seconds
let TICK=${TIMEOUT}/2-1

trap "" INT HUP

i2cset -y -f ${BUS} ${ADDR} 0x0F ${TIMEOUT}	# reset Timer
i2cset -y -f ${BUS} ${ADDR} 0x0E 0x82 # enable Timer countdown
i2cset -y -f ${BUS} ${ADDR} 0x01 0x11 # enable Timer interrupt

while true; do
	i2cset -y -f ${BUS} ${ADDR} 0x0f ${TIMEOUT} # reset Timer
	sleep ${TICK}
done
